name: Build and Package (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pkg (to package the EXE)
        run: npm install -g pkg

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build the project
        run: npm run build

      - name: Package for Windows
        run: pkg . --targets node18-win-x64 --output ./dist/meru.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: meru-exe
          path: ./dist/meru.exe
