name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Package for Windows
        if: matrix.os == 'windows-latest'
        run: npm run dist:window

      - name: Package for macOS
        if: matrix.os == 'macos-latest'
        run: npm run dist:mac

      - name: Package for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run dist:linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
